# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
highlighter: pygments
gems:
  - jemoji

# Site settings
title: "nodule.io"
description: > # this means to ignore newlines until "email:"
   Making Bluetooth Low Energy Work 

email: support@nodule.io
#blog logo
logo: "/assets/images/favicon.png"
# blog cover
cover: "/assets/images/cover.jpg"

name: 'CMG Research Ltd'
author: 'CMG Research Ltd'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://blog.nodule.io" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/noduleio
    desc: Follow us on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/noduleio
    desc:	View us on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
